-- MySQL Script generated by MySQL Workbench
-- Sat 29 Jul 2017 17:49:23 AWST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_ewetube
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_ewetube` ;

-- -----------------------------------------------------
-- Schema db_ewetube
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_ewetube` DEFAULT CHARACTER SET utf8mb4 ;
USE `db_ewetube` ;

-- -----------------------------------------------------
-- Table `db_ewetube`.`meat_produced`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_ewetube`.`meat_produced` ;

CREATE TABLE IF NOT EXISTS `db_ewetube`.`meat_produced` (
  `meat_id` INT(11) NOT NULL AUTO_INCREMENT,
  `meat_state` VARCHAR(50) CHARACTER SET 'utf8mb4' NOT NULL,
  `meat_animal` VARCHAR(50) CHARACTER SET 'utf8mb4' NOT NULL,
  `meat_unit` VARCHAR(50) CHARACTER SET 'utf8mb4' NOT NULL,
  `meat_datatype` VARCHAR(50) CHARACTER SET 'utf8mb4' NOT NULL,
  `meat_month` INT(2) NOT NULL,
  `meat_year` YEAR NOT NULL,
  `meat_sc_original` INT(11) NULL DEFAULT NULL,
  `meat_sc_seasonallyadjusted` INT(11) NULL DEFAULT NULL,
  `meat_sc_trend` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`meat_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 540
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
